-- SQLite



INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.607711	,	-70.5885588	,		'JOAQUÍN PALACIOS & PILOTO PARDO, PUENTE ALTO ,REGION METROPOLITANA,CHILE', '');
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.616912	,	-70.5668388	,		'CIRCUNVALACIÓN & CENTRAL, PUENTE ALTO ,REGION METROPOLITANA,CHILE',   '');
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.612281	,	-70.5575595	,		'LOS LOROS & GUAYACÁN, PUENTE ALTO ,REGION METROPOLITANA,CHILE', '');
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.574323	,	-70.5546275	,		'GABRIELA ORIENTE & CAMILO HENRÍQUEZ, PUENTE ALTO ,REGION METROPOLITANA,CHILE', '');
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.576587	,	-70.5766623	,		'GABRIELA ORIENTE & NEMESIO VICUÑA, PUENTE ALTO ,REGION METROPOLITANA,CHILE', '');
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.568828	,	-70.5840419	,		'ELISA CORREA & CONCHA Y TORO, PUENTE ALTO ,REGION METROPOLITANA,CHILE', '');
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.606337	,	-70.603317	,		'DOMINGO TOCORNAL & ACCESO SUR, PUENTE ALTO ,REGION METROPOLITANA,CHILE', '');
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.569408	,	-70.5835836	,		'LOS TOROS & CONCHA Y TORO, PUENTE ALTO ,REGION METROPOLITANA,CHILE	', '');
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.610105	,	-70.5549943	,		'TOME & EYZAGUIRRE, PUENTE ALTO ,REGION METROPOLITANA,CHILE	',	'');
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.616903	,	-70.6132829	,		'JUANITA & EYZAGUIRRE, PUENTE ALTO ,REGION METROPOLITANA,CHILE', '');	
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.586048	,	-70.580409	,		'LUIS MATTE & CONCHA Y TORO, PUENTE ALTO ,REGION METROPOLITANA,CHILE', '');
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.586881	,	-70.5912488	,		'LUIS MATTE & MALEBRAN, PUENTE ALTO ,REGION METROPOLITANA,CHILE', '');	
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.614807	,	-70.5960697	,		'NOCEDAL & EYZAGUIRRE, PUENTE ALTO ,REGION METROPOLITANA,CHILE',	''        );
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.595601	,	-70.5900344	,		'JORGE ROSS & JUAN DE DIOS MALEBRAN, PUENTE ALTO ,REGION METROPOLITANA,CHILE', ''   );
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.605843	,	-70.5757957	,		'BALMACEDA & EDUARDO CORDERO, PUENTE ALTO ,REGION METROPOLITANA,CHILE', ''     );
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.588237	,	-70.601149	,		'CRETA & LUIS MATTE, PUENTE ALTO ,REGION METROPOLITANA,CHILE',	'');
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.608518	,	-70.538346	,		'CAMILO INTERNACIONAL & 27 DE SEPTIEMBRE, PUENTE ALTO ,REGION METROPOLITANA,CHILE',	'' )	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.580754	,	-70.592462	,		'GABRIELA & JUAN DE DIOS MALEBRÁN, PUENTE ALTO ,REGION METROPOLITANA,CHILE'	, '')	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.621556	,	-70.5738455	,		'SAN PEDRO & COSTANERA, PUENTE ALTO ,REGION METROPOLITANA,CHILE', '' )	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.550056	,	-70.5660874	,		'CAMILO HENRÍQUEZ & LAGO YELCHO, PUENTE ALTO ,REGION METROPOLITANA,CHILE',	'')	;



INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.5592,-	,	-70.5588459	,		'CAMILO HENRÍQUEZ & DIEGO PORTALES, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.593459	,	-70.6003979	,		'PRIMAVERA & CRETA, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.623744	,	-70.5877634	,		'SAN PEDRO & LA COLONIA, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.627128	,	-70.5951334	,		'PARQUE SANTA FAUSTINA, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.614343	,	-70.5796854	,		'RAMÓN NÚÑEZ & ARTURO PRAT, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.573580	,	-70.6040041	,		'CRETA NORTE & CABO DE HORNOS, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.559249	,	-70.5525282	,		'SÁNCHEZ FONTECILLA & DIEGO PORTALES, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.604094	,	-70.5877017	,		'DOMINGO TOCORNAL & JUAN DE DIOS MALEBRAN, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.617173	,	-70.5677274	,		'CHARLES ARANGUIZ & GERMAN EBBINGHAUSS, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.551767	,	-70.553457	,		'SÁNCHEZ FONTECILLA & LAS PERDICES, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.555870	,	-70.5475712	,		'CAMINO SANTA ROSA DEL PERAL & EL ALBATROS, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.587610	,	-70.5967186	,		'LUIS MATTE LARRAÍN & EJÉRCITO LIBERTADOR, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.595964	,	-70.5846379	,		'JORGE ROSS OSSA & COQUIMBO, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.601194	,	-70.5836493	,		'COQUIMBO & INDEPENDENCIA, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.611406	,	-70.626569	,		'AV SANTA ROSA & CAMINO EL MARISCAL , PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.610122	,	-70.5919559	,		'DOMINGO TOCORNAL & EJÉRCITO LIBERTADOR, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.621142	,	-70.6126732	,		'JUANITA & SARGENTO MENADIER, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.583031	,	-70.6098333	,		'AV GABRIELA PONIENTE & CALETERA ACCESO SUR, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.606408	,	-70.6045346	,		'AV DOMINGO TOCORNAL & CALETERA ACCESO SUR, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.570501	,	-70.6113046	,		'AV CANAL TRONCAL SAN FRANCISCO & LA SERENA , PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.560904	,	-70.557448	,		'AV CAMILO HENRÍQUEZ & CALLE BAHÍA INGLESA, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.591489	,	-70.5426051	,		'AV TOBALABA & AV SAN CARLOS , PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.621538	,	-70.5737075	,		'AV CONCHA Y TORO & AV SAN PEDRO , PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.559220	,	-70.552562	,		'AV DIEGO PORTALES & AV SANCHEZ FONTECILLA , PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.5592,-	,	-70.5588459	,		'AV DIEGO PORTALES & AV CAMILO HENRIQUEZ, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.615694	,	-70.6033577	,		'AV EYZAGUIRRE & CAMINO EL RODEO , PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.618504	,	-70.6264528	,		'AV EYZAGUIRRE & AV SANTA ROSA, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.591089	,	-70.5669404	,		'NONATO COO & SAN HUGO, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.609381	,	-70.5177066	,		'EL QUISCO &  11 DE SEPTIEMBRE, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.629421	,	-70.6251891	,		'SAN PEDRO & CHILOÉ, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.586630	,	-70.5625562	,		'TRONCAL SAN FRANCISCO – MÉXICO, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.580166	,	-70.5690193	,		'NONATO COO & EL PEÑÓN, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.580485	,	-70.58139	,		'CONCHA Y TORO & EL PEÑÓN, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.584286	,	-70.6043374	,		'&SULTORIO BERNARDO LEIGHTON, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.573064	,	-70.5714039	,		'LABRADOR & NONATO COO, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.616397	,	-70.5794145	,		'CLAUDIO ARRAU & RAMÓN NUÑEZ, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.570007	,	-70.6092737	,		'TRONCAL SAN FRANCISCO & BAHÍA CATALINA, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.562107	,	-70.5380202	,		'DIEGO PORTALES & CANAL DE LA LUZ, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.597295	,	-70.5996906	,		'JORGE ROSS & CRETA, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.615521	,	-70.5866807	,		'ARTURO PRAT & SALVADOR ALLENDE, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.586622	,	-70.5863562	,		'COQUIMBO & LUIS MATTE, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.600625	,	-70.556536	,		'MÉXICO & DOMINGO TOCORNAL, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.581017	,	-70.611538	,		'ROSA ESTER & ACCESO SUR, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.619868	,	-70.598598	,		' ACCESO SUR & SARGENTO MENADIER, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.607040	,	-70.5600754	,		'JOSE LUIS COO 01120, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.596531	,	-70.557918	,		'MÉXICO & SAN CARLOS, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.591027	,	-70.542797	,		'SAN CARLOS &TOBALABA, PUENTE ALTO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.542134	,	-70.634108	,		'AV AMÉRICO VESPUCIO & SANTA ROSA,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.539789	,	-70.6512756	,		'AV AMÉRICO VESPUCIO & CORONEL ,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.539789	,	-70.6512756	,		'AV AMÉRICO VESPUCIO  & CORONEL,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.528922	,	-70.6354773	,		'AV SANTA ROSA & LINARES,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.541875	,	-70.6227385	,		'AVENIDA AMÉRICO VESPUCIO & OSMAN PEREZ FREIRE,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.556309	,	-70.6240643	,		'AVENIDA SAN JOSÉ DE LA ESTRELLA & JOAQUIN EDWARD BELLO,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.546417	,	-70.614937	,		'CORONEL & MANUEL RODRIGUEZ,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.542426	,	-70.6156395	,		'ESMERALDA & CORONEL,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.552638	,	-70.6210013	,		'PEDRO LIRA & LAS PARCELAS,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.523819	,	-70.6210402	,		'YUNGAY & MAÑIO,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.555784	,	-70.6202649	,		'AVENIDA SAN JOSÉ DE LA ESTRELLA & LAS PARCELAS,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.527302	,	-70.6227941	,		'LINARES & SERENA,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.524352	,	-70.625311	,		'CARDENAL RAUL SILVA HENRIQUE & YUNGAY,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.537692	,	-70.6245524	,		'EL TABO & SAN GREGORIO,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.542134	,	-70.612346	,		'ESMERALDA & ISLA TIERRA DEL FUEGO,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.546782	,	-70.6251898	,		'JOAQUÍN EDWARDS BELLO & VICUÑA MACKENNA,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.519842	,	-70.6236236	,		'LAS INDUSTRIAS & PADRE ESTEBAN GUMUCIO,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.526806	,	-70.6170036	,		'LINARES & CORONEL,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.530157	,	-70.6301355	,		'LOS VILOS & COMBARBALÁ,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.520689	,	-70.6313682	,		'LOS VILOS & PADRE ESTEBAN GUMUCIO,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.526442	,	-70.6291267	,		'MIGUEL ADASME & VICTORIA,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.520982	,	-70.6176861	,		'PADRE ESTEBAN GUMUCIO VIVES & CORONEL,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.552086	,	-70.6150708	,		'PEDRO LIRA & VICUÑA,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.537388	,	-70.6099092	,		'SAN GREGORIO & PUNTA ARENA,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.524989	,	-70.6310287	,		'SANTA ANA & LOS VILOS,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.551062	,	-70.629154	,		'SOFIA EASTMAN DE HUNEEUS & CANTO GENERAL,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.545216	,	-70.6130811	,		'TRICOLOR & ISLA QUIRIQUINA,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.552205	,	-70.61763	,		'CARDENAL RAUL SILVA HENRIQUE & PEDRO LIRA,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.515242	,	-70.619379	,		'CALLE P & LULA DA SILVA,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.550585	,	-70.6250981	,		'CANTO GENERAL & EDWARD BELLO,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.529085	,	-70.6167709	,		'CORONEL & COMBARBALÁ,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.549401	,	-70.6312436	,		'LAS UVAS Y EL VIENTO & EL PARQUE,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.543793	,	-70.6271185	,		'MANUEL RODRIGUEZ & TUPUNGATO,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.514904	,	-70.6154787	,		'MAÑIO & SEBASTOPOL,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.555156	,	-70.6283058	,		'SOFÍA EASTMAN DE HUNEEUS & CAPITAN AVALOS,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.520208	,	-70.627018	,		'CARDENAL RAUL SILVA HENRIQUE & PADRE ESTEBAN GUMUCIO,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.552564	,	-70.6247181	,		'JOAQUÍN EDWARDS BELLO & BENJAMIN SUBERCASEAUX,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.539391	,	-70.6342962	,		'MANUTARA & SANTA ROSA,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.535505	,	-70.621433	,		'PADRE JUAN MEYER & CARDENAL RAUL SILVA HENRIQUE,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.523955	,	-70.6359367	,		'AV SANTA ROSA & JOSE GHIARDO,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.518712	,	-70.627654	,		'CARDENAL RAUL SILVA HENRIQUE & CALLE E,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.529647	,	-70.6226176	,		'CARDENAL RAUL SILVA HENRIQUE & COMBARBALÁ,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.541202	,	-70.6239667	,		'EL TABO & ABELARDO NUÑEZ ,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.524077	,	-70.6229512	,		'LAS INDUSTRIAS & YUNGAY,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.537669	,	-70.6226682	,		'LONTUE & SAN GREGORIO,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.546408	,	-70.6169735	,		'MANUEL RODRIGUEZ & VICUÑA MACKENNA,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.534832	,	-70.6213681	,		'PARRAL & COMBARBALÁ CAMBIO DE CARDENAL RAUL SILVA HENRIQUE&TOME,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.554458	,	-70.6146057	,		'SAN JOSÉ DE LA ESTRELLA & VICUÑA,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.531562	,	-70.6165269	,		'TOME & CORONEL,LA GRANJA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.500353	,	-70.6664867	,		'JOSÉ JOAQUÍN PRIETO & DEPARTAMENTAL ,SAN MIGUEL ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.501394	,	-70.6625868	,		'DEPARTAMENTAL & CUARTA TRANSVERSAL ,SAN MIGUEL ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.494813	,	-70.6638022	,		'JOSÉ JOAQUÍN PRIETO& LA MARINA ,SAN MIGUEL ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.499377	,	-70.653809	,		'SAN NICOLÁS & GRAN AVENIDA ,SAN MIGUEL ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.500912	,	-70.654046	,		'GRAN AVENIDA & PIRÁMIDE,SAN MIGUEL ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.558064	,	-70.6311026	,		'SANTA ROSA& VENANCIA LEIVA,SAN RAMON,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.542134	,	-70.634108	,		'SANTA ROSA& AMERICO VESPUCIO SUR,SAN RAMON,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.542134	,	-70.634108	,		'SANTA ROSA & AMERICI VESPUCIO NORTE,SAN RAMON,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.541420	,	-70.643284	,		'METRO SAN RAMON LADO SUR ,SAN RAMON,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.543489	,	-70.6367626	,		'PEDRO AGUIRRE CERDA & AVENIDA OSSA,SAN RAMON,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.534147	,	-70.634905	,		'URUGUAY SANTA ROSA,SAN RAMON,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.544986	,	-70.6355697	,		'LOS FRANCISCANOS &JUAN BAUTISTA,SAN RAMON,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.544864	,	-70.6521253	,		'VICUÑA MAQUENA & SAN FRANCISCO,SAN RAMON,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.537738	,	-70.6345228	,		'DOÑIHUE& SANTA ROSA,SAN RAMON,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.553971	,	-70.6338586	,		'ESPERANZA&CAUPOLICAN,SAN RAMON,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.554999	,	-70.6545303	,		'VENANCIA LEIVA & SAN FRANCISCO,SAN RAMON,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.556339	,	-70.6455284	,		'VENANCIA LEIVA &ALMIRANTE LATORRE,SAN RAMON,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.542651	,	-70.642771	,		'AVOSSA &ALMIRANTE LATORRE,SAN RAMON,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.526704	,	-70.6357381	,		'SANTA ROSA & LOS MAITENES,SAN RAMON,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.540736	,	-70.6380807	,		'TIL TIL & INDEPENDENCIA,SAN RAMON,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.504634	,	-70.6237724	,		'LLICO & VECINAL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.481489	,	-70.6256382	,		'GLUCK & MOZART,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.480346	,	-70.6369707	,		'PACIFICO & RIVAS,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.482893	,	-70.6347175	,		'CARLOS VALDOVINOS & CARMEN,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.478562	,	-70.6368366	,		'YALTA & CARLOS SILVA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.476827	,	-70.635694	,		'PINTOR CICARELLI & CASABLANCA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.475904	,	-70.631337	,		'PINTO CICARELLI & LIRA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.473942	,	-70.632569	,		'SANTA MARIA & SIERRA BELLA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.482338	,	-70.6235884	,		'LISZT & SCHUBERT,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.490889	,	-70.640279	,		'MATTA VIAL & SANTA ROSA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.485285	,	-70.6410086	,		'SANTA ROSA & MATAVERI,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.495655	,	-70.6335331	,		'AV SALVADOR ALLENDE & MATEO DE TORO Y ZAMBRANO,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.504888	,	-70.6292697	,		'BENOZZO GOZOOLLI & LLICO,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.491730	,	-70.6222516	,		'AQUITECTO BRUNELLESCHI & EL PINAR,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.493816	,	-70.628992	,		'COMERCIO & LAS INDUSTRIAS,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.492578	,	-70.619053	,		'SAN JUAN & CASTELAR NORTE,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.490380	,	-70.6227114	,		'ALCALDE PEDRO ALAR& & FRANCISCA DE RIMINI,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.508516	,	-70.6303858	,		'FRANCISCO DE TOLEDO & INGENIERO MARIO DIAZ,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.505311	,	-70.6354971	,		'LLICO & DIEGO DE MEZA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.497878	,	-70.637186	,		'CABILDO & INGENIERO BUDGE,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.500953	,	-70.6370869	,		'CRISTOBAL DE ERAZO & URETA COX,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.502554	,	-70.6389327	,		'SAN NICOLAS & SANTA ROSA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.497480	,	-70.6299595	,		'BENOZZO GOZOOLLI & INGENIERO BUDGE,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.499361	,	-70.6360582	,		'PEDRO MIRA & DIEGO DE MEZA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.500557	,	-70.62264	,		'HAYDN & URETA COX,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.503398	,	-70.6300082	,		'PINTOR MURILLO & PIRAMIDE,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.501816	,	-70.6274495	,		'INDUSTRIAS & SAN NICOLAS,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.501121	,	-70.617095	,		'SAN JUAN & CAPITAN PRAT,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.499253	,	-70.620854	,		'CANADA & RAQUEL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.498353	,	-70.625036	,		'VECINA & GABRIEL MISTRAL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.485522	,	-70.6256111	,		'CARLOS VALDOVINOS & LAS FLORES,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.507585	,	-70.6231689	,		'DEPARTAMENTAL & VECINAL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.515513	,	-70.6368507	,		'LA CASTRINA & SANTA ROSA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.514896	,	-70.6310176	,		'LA CASTRINA & JUAN PLANAS,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.513024	,	-70.6301609	,		'GANGES & NAVARINO,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.510098	,	-70.632154	,		'SARMIENTO & JUAN PLANAS,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.507150	,	-70.6363467	,		'BERLIOZ & DEPARTAMENTAL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.514543	,	-70.6354382	,		'EL PRADO & PARSIFAL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.518581	,	-70.6354899	,		'CANTARES DE CHILE & LO OVALLE,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.514266	,	-70.6198936	,		'LO OVALLE & HAYDN,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.509477	,	-70.619776	,		'FRANCIA & CARMEN MENA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.512836	,	-70.634176	,		'BERLIOZ & VARAS MENAS,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.492630	,	-70.626702	,		'CASTELAR NORTE 250,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.507993	,	-70.6182391	,		'BRASILIA & DEPARTAMENTAL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.478847	,	-70.641748	,		'SANNTA ROSA & RIVAS,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.495264	,	-70.6396731	,		'SANTA ROSA & SALVADOR ALLENDE,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.496141	,	-70.628551	,		'LAS INDUSTRIAS & SALVADOR ALLENDE,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.507526	,	-70.626054	,		'LAS INDUSTRIA & DEPARTAMENTAL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.478255	,	-70.621997	,		'VICUÑA MACKENNA & SANTA ELENA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.487612	,	-70.6185794	,		'VICUÑA MACKENA & CARLOS VALDONINO,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.491604	,	-70.6176853	,		'VICUÑA MACKENA & EL PINAR,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.508684	,	-70.6133813	,		'VICUÑA MACKENA & DEPARTAMENTAL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.477183	,	-70.641799	,		'SANTA ROSA & PINTO CICARELLI,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.488098	,	-70.64057	,		'SANTA ROSA & PEDRO ALAR&,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.500731	,	-70.6336046	,		'URETA COX & JUAN GRIEGO,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.513067	,	-70.6374378	,		'SAN ROSA & VARAS MENA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.484452	,	-70.6294065	,		'CARLOS VALDOVINOS & LAS INDUSTRIAS,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.490321	,	-70.629531	,		'LAS INDUSTRIAS & PEDRO ALAR&,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.502240	,	-70.6334672	,		'SAN NICOLAS & JUAN GRIEGO,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.5099,-	,	-70.630962	,		'PINTOR DURERO & PEDRO SARMIENTO,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.514014	,	-70.629262	,		'PINTOR DURERO & POMPEYA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.512401	,	-70.6281365	,		'VARAS MENA & PINTOR MURILLO,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.516175	,	-70.628255	,		'SEBASTOPOL & LA TINOAMERICANA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.473454	,	-70.6261206	,		'SANTA ELENA & CARLOS FERNANDEZ CONCHA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.479624	,	-70.6255466	,		'JUAN SEBASTIAN BASCH & HAYDN,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.485372	,	-70.6202688	,		'VICUÑA MACKENNA  & ISABEL RIQUELME,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.496038	,	-70.6163202	,		'VICUÑA MACKENNA & SALVADOR ALLENDE,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.499915	,	-70.619466	,		'IQUIQUE & MANUEL PEREZ,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.498535	,	-70.6157093	,		'VICUÑA MACKENNA & RAQUEL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.513123	,	-70.613659	,		'LO OVALLE & PARQUER ESTADIO ,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.518167	,	-70.6317221	,		'LO OVALLE & LA TRANQUERA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.514755	,	-70.6207893	,		'LO OVALLE  & VECINAL ,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.511871	,	-70.6203828	,		'VARAS MENA & HAYD,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.507920	,	-70.6209749	,		'DEPARTAMENTAL & HAYDS,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.490380	,	-70.6227114	,		'CARLOS VALDOVINOS & FRANCISCA RIMINI,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.477718	,	-70.6327934	,		'TOCORNAL & CARLOS SILVA VILDOSOLA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.496335	,	-70.6234262	,		'SALVADOR ALLENDE & HAYDN,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.496511	,	-70.6361277	,		'GASPAR DE SOTO & SAN GREGORIO,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.505679	,	-70.6235408	,		'QUILLAHUA & VECINAL ,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.489722	,	-70.63116	,		'CANIN & SCHWAGER,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.494074	,	-70.621036	,		'COMERCIO & GEORGE BIZET,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.492466	,	-70.6238655	,		'CASTELAR NORTE & CENTRAL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.492466	,	-70.6238655	,		'CASTELAR NORTE & CENTRAL FIJA ,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.492086	,	-70.633351	,		'MATEO TORO Y ZAMBRANO & ALVAREZ TOLEDO,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.495972	,	-70.6300971	,		'PRIMERO DE MAYO & PEDRO ALAR&,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.487316	,	-70.6280726	,		'SALOMOR SUMAR & FRANCIS DRAKE,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.483629	,	-70.6321677	,		'CARLOS VALDOVINOS & SIERRA BELLA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.477451	,	-70.6282043	,		'DIAGONAL SANTA ELENA & DEBUSSY,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.509357	,	-70.623391	,		'VECINAL & CARMEN MENA ,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.502004	,	-70.6301593	,		'PINTOR MURILLO & SAN NICOLAS,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.503597	,	-70.630064	,		'PINTOR MURIILO & PLAZA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.484452	,	-70.6294065	,		'CARLOS VALDONIVOS & LAS INDUSTRIAS,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.480885	,	-70.641908	,		'SAN ROSA & CARLOS VALDONIVOS,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.480885	,	-70.641908	,		'SAN ROSA & CARLOS VALDONIVOS,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.495264	,	-70.6396731	,		'SANTA ROSA & AV SALVADOR ALLENDE ,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.485414	,	-70.6297797	,		'LAS INDUSTRIAS & GANDARILLA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.507264	,	-70.6386952	,		'SANTA ROSA & DEPARTAMENTAL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.517008	,	-70.6369658	,		'SANTA ROSA & SEBASTOPOL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.474810	,	-70.634982	,		'CARMEN & SANTA MARIA ,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.471806	,	-70.6239189	,		'CELIA SOLAR & VICUÑA MACKENA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.514755	,	-70.6207893	,		'LO OVALLE  & VECINAL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.511871	,	-70.6203828	,		'VARAS MENA &  HAYDN,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.480795	,	-70.6307723	,		'ISABEL RIQUELME & SIERRA BELLA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.480795	,	-70.6307723	,		'ISABEL RIQUELME & SIERRA BELLA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.510880	,	-70.6170019	,		'VARAS MENA & BRASILIA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.516429	,	-70.6242153	,		'LO OVALLE & LAS INDUSTRIA,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.506992	,	-70.6260029	,		'LAS INDUSTRIA & JORGE QUEVEDO,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.507865	,	-70.615847	,		'DEPARTAMENTAL & SAN JUAN ,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.507514	,	-70.626222	,		'LAS INDUSTRIAS & DEPARTAMENTAL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.496321	,	-70.623439	,		'CENTRAL & SALVADOR ALLENDE,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.491604	,	-70.6176853	,		'VICUÑA MACKENNA & EL PINAR,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.498500	,	-70.616208	,		'VICUÑA MACKENA & RAQUEL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.505679	,	-70.6235408	,		'QUILLAHUA &VECINAL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.490889	,	-70.640279	,		'SANTA ROSA & MATA VIAL,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.501078	,	-70.617062	,		'SAN JUAN &  CAPITAN PRAT,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.490307	,	-70.62938	,		'LAS INDUSTRIAS & PEDRO ALAR&,SAN JOAQUIN ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.523626	,	-70.6984525	,		'AV AMÉRICO VESPUCIO & AV CENTRAL CARDENAL RAÚL SILVA HENRÍQUEZ ,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.523626	,	-70.6984525	,		'AV AMÉRICO VESPUCIO & AV CENTRAL CARDENAL RAÚL SILVA HENRÍQUEZ ,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.522180	,	-70.6974503	,		'AV CENTRAL CARDENAL RAÚL SILVA HENRÍQUEZ & PASAJE OSSA MENOR,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.521428	,	-70.696905	,		'PASAJE PEGASO & AV CENTRAL CARDENAL RAÚL SILVA HENRÍQUEZ,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.524356	,	-70.6957937	,		'AV AMÉRICO VESPUCIO & DIAGONAL LAS TORRES,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.516821	,	-70.7011666	,		'AV EDUARDO FREI MONTALVA & PASAJE 6 PONIENTE,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.520301	,	-70.6869654	,		'AV CLOTARIO BLEST & AV ADOLFO LÓPEZ MATEO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.516219	,	-70.686044	,		'AV CLOTARIO BLEST & AV PRESIDENTE SALVADOR ALLENDE GOSSENS,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.519469	,	-70.675687	,		'AV PRESIDENTE SALVADOR ALLENDE GOSSENS & AV JOSÉ JOAQUÍN PRIETO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.523098	,	-70.6772436	,		'AV ADOLFO LÓPEZ MATEO & AV JOSÉ JOAQUÍN PRIETO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.524393	,	-70.6990321	,		'CALLE GIL DE CASTRO & AV CENTRAL CARDENAL RAÚL SILVA HENRÍQUEZ,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.517702	,	-70.681278	,		'AV PRESIDENTE SALVADOR ALLENDE GOSSENS & CALLE HUASCO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.526437	,	-70.6997035	,		'CALLE 9 DE ENERO & AV GABRIELA MISTRAL,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.522187	,	-70.6802798	,		'AV ADOLFO LÓPEZ MATEO & CALLE ACAPULCO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.519509	,	-70.6956656	,		'AV CENTRAL CARDENAL RAÚL SILVA HENRÍQUEZ & AV EDUARDO FREI MONTALVA,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.506524	,	-70.691525	,		'CALLE BUENAVENTURA & CALLE LA HABANA,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.521579	,	-70.699644	,		'CALLE LA HABANA & AV AMÉRICO VESPUCIO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.513249	,	-70.694883	,		'AV PRESIDENTE SALVADOR ALLENDE GOSSENS & CALLE LA HABANA,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.532885	,	-70.7026066	,		'AV LO ESPEJO & AV GABRIELA MISTRAL,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.519467	,	-70.675795	,		'AV JOSÉ JOAQUÍN PRIETO & AV PRESIDENTE SALVADOR ALLENDE GOSSENS,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.532172	,	-70.6935216	,		'CALLE BALMACEDA & CALLE ASTABURUAGA,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.522862	,	-70.688333	,		'AV DEL FERROCARRIL & AV EDUARDO FREI MONTALVA,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.514880	,	-70.673515	,		'AV LINCOLN & AV JOSÉ JOAQUÍN PRIETO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.518197	,	-70.675007	,		'PASAJE CADERA & AV JOSÉ JOAQUÍN PRIETO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.510318	,	-70.684499	,		'AV LINCOLN & AV CLOTARIO BLEST,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.510688	,	-70.6713253	,		'AV LO OVALLE & AV JOSÉ JOAQUÍN PRIETO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.503577	,	-70.690756	,		'AV LO OVALLE & AV CENTRAL CARDENAL RAÚL SILVA HENRÍQUEZ,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.506262	,	-70.6828655	,		'AV LO OVALLE & AV CLOTARIO BLEST,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.527723	,	-70.6901098	,		'AV DEL FERROCARRIL & AV AMÉRICO VESPUCIO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.523921	,	-70.6779403	,		'AV AMÉRICO VESPUCIO & AV JOSÉ JOAQUÍN PRIETO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.513925	,	-70.692892	,		'AV PRESIDENTE SALVADOR ALLENDE GOSSENS & AV CENTRAL CARDENAL RAÚL SILVA HENRÍQUEZ,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.532725	,	-70.697532	,		'CALLE CENTENARIO & CALLE MAIPÚ,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.507385	,	-70.688854	,		'CALLE BUENAVENTURA & CALLE COOPERACIÓN,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.527742	,	-70.6911314	,		'ASTABURUAGA & AV AMÉRICO VESPUCIO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.512908	,	-70.688352	,		'CALLE ACAPULCO & CALLE OBISPO JAVIER VÁSQUEZ ,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.514993	,	-70.6957502	,		'PASAJE 19 SUR & HABANA,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.525049	,	-70.6781848	,		'EDUARDO FREI MONTALVA & JOSÉ JOAQUÍN PRIETO VIAL,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.522615	,	-70.6996826	,		'CALETERA AMÉRICO VESPUCIO & VALENZUELA LLANOS,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.531535	,	-70.682967	,		'CALETERA AMÉRICO VESPUCIO &  AUTOPISTA CENTRAL,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.522752	,	-70.7034677	,		'JUAN FRANCISCO GONZÁLEZ & MARCELA PAZ,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.523261	,	-70.7003814	,		'GIL DE CASTRO & VALENZUELA LLANOS,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.509382	,	-70.6743456	,		'AV LO OVALLE & VALPARAISO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.513881	,	-70.6855397	,		'CLOTARIO BLEST & LUCILA GODOY,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.527742	,	-70.6911314	,		'ASTABURUAGA & AMERICO VESPUCIO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.511741	,	-70.699172	,		'SALVADOR ALLENDE & ALBERTO HURTADO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.514665	,	-70.6907649	,		'SALVADOR ALLENDE & VERACRUZ,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.523263	,	-70.685214	,		'DURAZNO & EDUARDO FREI,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.511782	,	-70.691874	,		'11 SUR & AV CENTRAL,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.502916	,	-70.692846	,		'CALLE AZTECA & LO OVALLE,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.512530	,	-70.6790526	,		'LINCOLN & HUASCO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.514732	,	-70.675638	,		'ZAPIGA & HUARA,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.504968	,	-70.6958914	,		'CERRILLOS & BUENAVENTURA,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.515053	,	-70.6858066	,		'AVENIDA CLOTARIO BLEST & CODEGUA,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.509222	,	-70.6775601	,		'PASAJE 38 6521,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.513459	,	-70.676829	,		'AVENIDA VALPARAÍSO & LINCOLN,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.511894	,	-70.6986949	,		'AVENIDA SALVADOR ALLENDE & 6 PONIENTE,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.513881	,	-70.6855397	,		'LUCILA GODOY & CLOTARIO BLEST,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.513712	,	-70.6863982	,		'SANTA ANITA & ACAPULCO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.517019	,	-70.6836178	,		'ISABEL RIQUELME & SALVADOR ALLENDE,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.518350	,	-70.6792921	,		'SALVADOR ALLENDE & EL PARRÓN,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.517599	,	-70.699586	,		'PIO XII & EDUARDO FREI MONTALVA,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.523103	,	-70.685945	,		'EDUARDO FREI MONTALVA & PACHUCA,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.522374	,	-70.6900836	,		'EDUARDO FREI MONTALVA & CALLE 1,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.520932	,	-70.6842111	,		'ADOLFO LÓPEZ MATEO & DURAZNO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.526017	,	-70.6930694	,		'AMÉRICO VESPUCIO & UNICORNIO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.518816	,	-70.7003997	,		'PIO XII & LEBRELES,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.524782	,	-70.6792355	,		'EDUARDO FREI MONTALVA & HERMOSILLO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.532433	,	-70.7039212	,		'AVENIDA LO ESPEJO & JUAN FRANCISCO GONZÁLEZ,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.533325	,	-70.6905793	,		'CENTENARIO & JORGE GUERRA SQUELLA,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.511715	,	-70.699204	,		'SALVADOR ALLENDE & CERRILLOS,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.531923	,	-70.7049698	,		'AVENIDA LO ESPEJO & DON MIGUEL ÁNGEL,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.538847	,	-70.686007	,		'AVENIDA LO ESPEJO & JOSÉ JOAQUÍN PRIETO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.521168	,	-70.6763201	,		'AVENIDA EL PARRÓN & JOSÉ JOAQUÍN PRIETO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.530844	,	-70.681475	,		'AMÉRICO VESPUCIO & JOSÉ JOAQUÍN PRIETO,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.502289	,	-70.6946104	,		'LO OVALLE & CERRILLOS,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.520417	,	-70.701448	,		'AMÉRICO VESPUCIO & PIO XII,LO ESPEJO ,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.546367	,	-70.6667217	,		'AVDA PADRE HURTADO & ERNESTO RIQUELME,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.554874	,	-70.6691093	,		'AVDA PADRE HURTADO & ALEJANDRO GUZMÁN,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.560218	,	-70.6705486	,		'AVDA PADRE HURTADO & OBSERVATORIO,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.566466	,	-70.6721732	,		'AVDA PADRE HURTADO & CLAUDIO ARRAU,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.558154	,	-70.6558503	,		'AVDA SAN FRANCISCO & ALEJANDRO GUZMÁN,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.562348	,	-70.6568447	,		'AVDA SAN FRANCISCO & OBSERVATORIO,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.558980	,	-70.6786742	,		'GRAN AVDA JOSÉ MIGUEL CARRERA & OBSERVATORIO,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.553538	,	-70.6744512	,		'GRAN AVDA JOSÉ MIGUEL CARRERA & ALEJANDRO GUZMÁN,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.545508	,	-70.668261	,		'GRAN AVDA JOSÉ MIGUEL CARRERA & ERNESTO RIQUELME,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.549077	,	-70.6710918	,		'GRAN AVDA JOSÉ MIGUEL CARRERA & VICTOR PLAZA MAYORGA,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.562956	,	-70.6713912	,		'AVDA PADRE HURTADO & LOS SAUCES,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.542012	,	-70.684269	,		'CAPRICORNIO & DIECIOCHO DE SEPTIEMBRE,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.565107	,	-70.6836634	,		'GRAN AVDA JOSÉ MIGUEL CARRERA & HUMBERTO ALLENDE,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.572698	,	-70.6661384	,		'AV LO MARTÍNEZ & TUCAPEL,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.559830	,	-70.6580264	,		'ARAUCARIAS & LAS CHOGUITAS,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.555440	,	-70.6574249	,		'ALMIRANTE RIVEROS & AV SUR,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.576337	,	-70.6921823	,		'LO BLANCO & GRAN AVENIDA,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.566508	,	-70.660407	,		'SANTA ELENA & LAS PERLAS,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.572954	,	-70.7008146	,		'OCHAGAVIA & LO BLANCO,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.556159	,	-70.6639111	,		'ALEJANDRO GUZMÁN & ELEUTERIO RAMÍREZ,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.550157	,	-70.684513	,		'RENGO LUIS & BARROS BORGOÑO,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.573745	,	-70.6878919	,		'CAMINO DEL INCA & MAURICIO RUGENDA,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.577232	,	-70.6636966	,		'GENERAL SILVA & NUEVA IMPERIAL,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.581979	,	-70.6766493	,		'JOSÉ MERCEDES ORTEGA & AV PADRE HURTADO,EL BOSQUE,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.514674	,	-70.6581956	,		'GRAN AVDA JOSÉ MIGUEL CARRERA & AV LO OVALLE,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.517005	,	-70.6588445	,		'GRAN AVDA & CALLE CARVAJAL,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.518563	,	-70.6592812	,		'GRAN AVDA JOSÉ MIGUEL CARRERA & CALLE SANTA ELISA ,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.526521	,	-70.6613882	,		'GRAN AVDA JOSÉ MIGUEL & AV EL PARRÓN ,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.527544	,	-70.6616815	,		'GRAN AVDA JOSÉ MIGUEL & CALLE ABEL GONZÁLEZ,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.530033	,	-70.6623217	,		'GRAN AVDA JOSÉ MIGUEL CARRERA & CALLE RAMÓN CARVALLO,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.533294	,	-70.6631327	,		'GRAN AVDA JOSÉ MIGUEL & BRISAS DEL MAIPO,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.535272	,	-70.6637239	,		'GRAN AVDA JOSÉ MIGUEL & AVDA PEDRO AGUIRRE CERDA ,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.537495	,	-70.6646926	,		'GRAN AVDA JOSÉ MIGUEL CARRERA & AVDA AMÉRICO VESPUCIO SUR ,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.537495	,	-70.6646926	,		'GRAN AVDA JOSÉ MIGUEL CARRERA & AV AMÉRICO VESPUCIO NORTE ,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.538819	,	-70.6648136	,		'GRAN AVDA JOSÉ MIGUEL CARRERA & AV OSSA ,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.540071	,	-70.6651433	,		'GRAN AVDA JOSÉ MIGUEL CARRERA & CALLE GOYCOLEA,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.542528	,	-70.6657704	,		'GRAN AVDA JOSÉ MIGUEL CARRERA & CALLE VICUÑA MACKENNA ,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.545508	,	-70.668261	,		'GRAN AVDA & RIQUELME,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.533722	,	-70.672712	,		'AUGUSTO VIAL & PAZ,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.538427	,	-70.6612979	,		'AMÉRICO VESPUCIO & CONCHA,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.536145	,	-70.6674448	,		'AMÉRICO VESPUCIO & PAULINA,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.538283	,	-70.659602	,		'AMÉRICO VESPUCIO & COBIJA,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.538935	,	-70.6584746	,		'AMÉRICO VESPUCIO & SAN CARLOS,LA CISTERNA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.584553	,	-70.645876	,		'GABRIELA & LOS LIMONEROS,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.588630	,	-70.6281556	,		'LO BLANCO & SANTA ROSA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.582094	,	-70.6601685	,		'TTE LUIS CRUZ MARTÍNEZ & PASAJE IMPERIAL ,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.573812	,	-70.6600838	,		'LO MARTÍNEZ & SAN FRANCISCO,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.560313	,	-70.6482989	,		'VIOLETA PARRA & LA BANDERA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.610438	,	-70.6376373	,		'EL MARISCAL & LOS DURAZNOS,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.561105	,	-70.6344839	,		'VIOLETA PARRA & POETA MIGUEL HERNÁNDEZ,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.618135	,	-70.6266463	,		'SANTA ROSA & LOS NOGALES,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.582147	,	-70.6197861	,		'ROSA ESTER & JUANITA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.560663	,	-70.61524	,		'ACCESO SUR & GENERAL ARRIAGADA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.579478	,	-70.6421455	,		'PUNTA DE HORCÓN & BERNARDINO PARADA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.558366	,	-70.6377473	,		'PEDRO AGUIRRE CERDA & DEL SEMBRADOR,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.578738	,	-70.649329	,		'PEDRO PRADO & BERNARDINO PARADA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.559758	,	-70.6562382	,		'VIOLETA PARRA & SAN FRANCISCO,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.578969	,	-70.6385326	,		'PORTO ALEGRE & JOSÉ MANUEL BALMACEDA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.587682	,	-70.6189326	,		'CALLE JUANITA  13458 ,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.563833	,	-70.622361	,		'JOAQUÍN EDWARDS BELLO & SAN MIGUEL ,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.594304	,	-70.607855	,		'LA PRIMAVERA & LA SERENA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.591656	,	-70.608275	,		'LA SERENA & MARTINIANO URRIOLA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.594647	,	-70.61111	,		'LA PRIMAVERA & CALLE 6,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.589831	,	-70.609015	,		'LA SERENA & BATALLÓN CHACABUCO,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.559812	,	-70.615498	,		'LA SERENA & EL KULTRÚN,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.585264	,	-70.609588	,		'LA SERENA & MIGUEL ANGEL,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.583179	,	-70.610727	,		'LA SERENA & GABRIELA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.583741	,	-70.615041	,		'GABRIELA & COLEGIO NUEVA NAZARETH,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.584342	,	-70.619431	,		'GABRIELA & JUANITA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.571793	,	-70.6594055	,		'SAN FRANCISCO & PASAJE 4,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.588002	,	-70.6354358	,		'LO BLANCO & DIAGONAL GABRIELA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.585572	,	-70.628771	,		'SANTA ROSA & GABRIELA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.582915	,	-70.6288254	,		'SANTA ROSA & BALDOMERO LILLO,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.582516	,	-70.6341809	,		'BALDOMERO LILLO & PATAGONIA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.585650	,	-70.631594	,		'ANIBAL PINTO & GABRIELA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.565738	,	-70.6302166	,		'SANTA ROSA & OBSERVATORIO,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.565257	,	-70.6352496	,		'OBSERVATORIO & POETA MIGUEL HERNÁNDEZ,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.582438	,	-70.6766381	,		'LO BLANCO & PADRE HURTADO,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.564502	,	-70.6401556	,		'OBSERVATORIO & SANTA IRMA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.564106	,	-70.643151	,		'OBSERVATORIO & EL NOGAL,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.586754	,	-70.6495746	,		'LO BLANCO & JHON KENNEDY,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.563644	,	-70.6468361	,		'OBSERVATORIO & ALMIRANTE LATORRE,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.565548	,	-70.6243507	,		'OBSERVATORIO & GABRIELA FIGUEROA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.562659	,	-70.654329	,		'OBSERVATORIO & LAS LOICAS,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.562348	,	-70.6568447	,		'OBSERVATORIO & SAN FRANCISCO,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.570501	,	-70.6113046	,		'LA SERENA & TRONCAL SAN FRANCISCO,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.563896	,	-70.6137833	,		'OBSERVATORIO & LA SERENA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.574777	,	-70.653334	,		'LO MARTÍNEZ & JOSE E BELLO,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.575348	,	-70.6486859	,		'LO MARTÍNEZ & PEDRO PRADO,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.576370	,	-70.638285	,		'LO MARTÍNEZ & PORTO ALEGRE,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.563129	,	-70.650506	,		'OBSERVATORIO & FRANCISCO DE GOYA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.560938	,	-70.639501	,		'VIOLETA PARRA & SANTA IRMA,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.577105	,	-70.629558	,		'SANTA ROSA & LO MARTÍNEZ,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.595090	,	-70.627586	,		'SANTA ROSA & EL OMBÚ,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.585190	,	-70.663253	,		'LO BLANCO & SAN FRANCISCO,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.559794	,	-70.630708	,		'SANTA ROSA & LOS MANANTIALES,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.556447	,	-70.616207	,		'LA SERENA & SANTO TOMÁS,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.594998	,	-70.614955	,		'LA PRIMAVERA & EL MAÑÍO,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.558242	,	-70.623577	,		'SANTO TOMÁS & JOAQUÍN EDWARD BELLO,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.582833	,	-70.662557	,		'PAICAVI & SAN FRANCISCO,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.600064	,	-70.627385	,		'SANTA ROSA & PAICAVÍ,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.557899	,	-70.634451	,		'VENANCIA LEIVA & CAUPOLICÁN,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
INSERT INTO camaras (latitud, longitud, propietario, contacto) VALUES	(	-33.591552	,	-70.62784	,		'SANTA ROSA & BATALLÓN CHACABUCO,LA PINTANA,REGION METROPOLITANA,CHILE		,			)	;
